package com.mle.musicpimp.json

/**
 * @author Michael
 */
object JsonStrings {
  val CMD = "cmd"
  val PING = "ping"
  val PING_AUTH = "ping_auth"
  val AUTHENTICATE = "authenticate"
  val FOLDER = "folder"
  val ROOT_FOLDER = "root_folder"
  val ALARMS = "alarms"
  val ALARMS_EDIT = "alarms_edit"
  val ALARMS_ADD = "alarms_add"
  val SEARCH = "search"
  val TERM = "term"
  val LIMIT = "limit"
  val BEAM = "BEAM"
  val ID = "id"
  val TRACK = "track"
  val REQUEST_ID = "request"
  val SERVER_KEY = "s"
  val REGISTERED = "registered"
  val UNREGISTER = "unregister"
  val EVENT = "event"
  val USERNAME = "username"
  val PASSWORD = "password"
  val BODY = "body"
  val VERSION = "version"
  val REASON = "reason"
  val STATUS = "status"
  val META = "meta"
  val SUCCESS = "success"
  val PHONES = "phones"
  val SERVERS = "servers"
  val REQUESTS = "requests"
  val ADDRESS = "address"
  val PLAYER = "player"
}
